yadm: slight tweaks to bootstrap scripts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -20,14 +20,24 @@ abort() {
 declare -rx YADM_DIR="${HOME}/.config/yadm"
 declare -rx BOOTSTRAP_DIR="${YADM_DIR}/bootstrap.d"
 declare -rx PACKAGE_DIR="${YADM_DIR}/package_lists"
+declare -r DOTFILES_REPO="git@github.com:JoaoPPinto/dotfiles.git"
 
 if [[ ! -d "$BOOTSTRAP_DIR" ]]; then
     abort "Error: bootstrap directory '$BOOTSTRAP_DIR' not found\n"
 fi
 
+printf "Checking and setting zsh as default shell\n"
+if ! echo "${SHELL}" | grep -q '/zsh'; then
+    sudo dnf install --assumeyes --quiet zsh || abort "Failed to install zsh"
+    sudo chsh -s "$(command -v zsh)" "$(whoami)" || abort "Failed to change shell"
+    abort "Restart shell so that zsh environment is setup. then re-run 'yadm bootstrap'"
+else
+    printf "zsh is already set as your default shell"
+fi
+
 # Update origin URL to use SSH
 printf "Updating the yadm repo origin URL\n"
-yadm remote set-url origin "git@github.com:JoaoPPinto/dotfiles.git"
+yadm remote set-url origin "$DOTFILES_REPO" || abort "Failed to update yadm repo origin URL"
 
 # Set yadm hooks and initialize submodules
 printf "Setting yadm hooks and initializing submodules\n"
@@ -40,18 +50,10 @@ for file in "${original_zsh_files[@]}"; do
   rm -rf "${file}"
 done
 
-# set zsh as shell
-if ! echo "${SHELL}" | grep -q '/zsh'; then
-	rpm -q zsh || sudo dnf install --assumeyes --quiet zsh
-	sudo chsh -s "$(command -v zsh)" "$(whoami)"
-	abort "Restart shell so that zsh environment is setup. Then re-run 'yadm bootstrap'"
-else
-	printf "zsh is already set as your default shell"
-fi
-
 # Run all bootstrap scripts in bootstrap.d
-command find -L "$BOOTSTRAP_DIR" -type f | sort -V | while IFS= read -r bootstrap; do
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+command find -L "$BOOTSTRAP_DIR" -type f -executable | sort -V | while IFS= read -r bootstrap; do
+    if [[ ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then # Exclude files with "##" or ending with "~"
+	printf "Executing: $bootstrap\n"
         if ! "$bootstrap"; then
             abort "Error: bootstrap '$bootstrap' failed"
         fi
