yadm: during bootstrap, change origin to ssh url

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -22,9 +22,13 @@ declare -rx BOOTSTRAP_DIR="${YADM_DIR}/bootstrap.d"
 declare -rx PACKAGE_DIR="${YADM_DIR}/package_lists"
 
 if [[ ! -d "$BOOTSTRAP_DIR" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_DIR' not found" >&2
+    echo "Error: bootstrap directory '$BOOTSTRAP_DIR' not found\n" >&2
     exit 1
 fi
+
+# Update origin URL to use SSH
+echo "Updating the yadm repo origin URL\n"
+yadm remote set-url origin "git@github.com:JoaoPPinto/dotfiles.git"
 
 # Set yadm hooks and initialize submodules
 printf "Setting yadm hooks and initializing submodules\n"
@@ -50,8 +54,7 @@ fi
 find -L "$BOOTSTRAP_DIR" -type f | sort | while IFS= read -r bootstrap; do
     if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
         if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
+            abort "Error: bootstrap '$bootstrap' failed"
         fi
     fi
 done
